services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ucc_space_test
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  jenkins:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: ucc_space_test
      DOCKER_HOST: tcp://host.docker.internal:2375
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - $HOME/jenkins_data:/var/jenkins_home

volumes:
  pgdata:
  jenkins_home:

