default: &default
  adapter: postgresql
  encoding: unicode
  username: 'postgres'
  database: 'ucc_space_database'
  password: 'postgres'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ucc_space_development
  port: 5432
  host: localhost

test:
  <<: *default
  database: 'ucc_space_test'
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: postgres
  password: postgres

production:
  <<: *default
  database: ucc_space_production
  username: ucc_space
  password: <%= ENV["UCC_SPACE_DATABASE_PASSWORD"] %>

